# Appium Configuration
appium.url=http://0.0.0.0:4723/wd/hub

# Device Capabilities
device.platformName=Android
device.platformVersion=9
device.automationName=UIAutomator2
device.unicodeKeyboard=true

# App path (relative to project root)
app.path=src/test/resources/application/app-release.apk

# Timeouts (seconds)
timeout.implicit=30
timeout.poll=1000
